# --- Dev stage ---
FROM node:20.19.0 AS dev
WORKDIR /app
COPY package*.json tsconfig*.json ./
RUN npm ci
ENV NODE_ENV=development
CMD ["npm", "run", "dev"]

# --- Prod stage ---
FROM node:20.19.0-slim AS runner
WORKDIR /app
COPY package*.json tsconfig*.json ./
RUN npm ci --omit=dev
COPY . .
ENV NODE_ENV=production
EXPOSE 4000
CMD ["npm", "start"]